### ISSUE TITLE
Cant see API keys in Admin

### ISSUE THREAD

**Issue by DjuriSchiffer** [cedaro/satispress#162] opened 2021-07-26 11:45 UTC
Hi there, 

I've installed 1.0.1 and I can't see the API keys in the Admin. 
![satis_admin](https://user-images.githubusercontent.com/67950991/126983349-4cde37e2-2e12-4c58-a458-052c5e25d7aa.png)

I've used the troubleshoot page https://github.com/cedaro/satispress/blob/develop/docs/troubleshooting.md#basic-auth-not-working but unfortunately with no success.

**Comment by bradyvercher** [comment] 2021-08-02 16:58
@DjuriSchiffer Have you checked the developer console in your browser to be sure there aren't any JavaScript errors? It looks like something isn't loading correctly.

**Comment by DjuriSchiffer** [comment] 2021-09-15 08:48
@bradyvercher Thanks, I've checked the developer console. There I see two JavaScript errors, I'll provide one of them as a screenshot below. 
![satispress-error](https://user-images.githubusercontent.com/67950991/133401799-f0ee5a76-dd92-4155-b691-e30c5284071a.png)

**Comment by bradyvercher** [comment] 2022-01-07 17:56
I can't tell whether that's an error generated by SatisPress or a conflict caused by another plugin. I haven't seen any other reports, so I'm going to go ahead and close this. If you can trace it to an issue in SatisPress, please feel free to reopen.

**Closed by bradyvercher** 2022-01-07 17:56 UTC
